// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proxytrace.Storage;

#nullable disable

namespace Proxytrace.Storage.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Endpoint")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAgent")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("IsSystemAgent");

                    b.HasIndex("Project", "IsArchived");

                    b.HasIndex("Project", "Name");

                    b.ToTable("AgentEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.AgentCall.AgentCallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InputTokens")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OutputTokens")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentVersionId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EndpointId");

                    b.ToTable("AgentCallEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.AgentVersion.AgentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LooseFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("AgentId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("Project", "Fingerprint")
                        .IsUnique();

                    b.HasIndex("Project", "LooseFingerprint");

                    b.ToTable("AgentVersionEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ApiKey.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Provider")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.HasIndex("Provider");

                    b.ToTable("ApiKeyEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ApplicationError.ApplicationErrorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ApplicationErrorEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Evaluator.EvaluatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("Project", "IsArchived");

                    b.ToTable("EvaluatorEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Invite.InviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InviteEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Licensing.StoredLicenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jwt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StoredLicenseEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Model.ModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("InputTokenCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Model")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OutputTokenCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("Provider")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Model", "Provider")
                        .IsUnique();

                    b.HasIndex("Provider", "IsArchived");

                    b.ToTable("ModelEndpointEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelProviderEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.OptimizationProposal.OptimizationProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ABTestRun")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdoptedAgentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AdoptedAgentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AdoptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("AdoptedManually")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Agent")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentPassRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceTestRunIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double?>("ProposedPassRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ABTestRun");

                    b.HasIndex("AdoptedAgentVersionId");

                    b.HasIndex("Agent");

                    b.HasIndex("Kind");

                    b.HasIndex("Status");

                    b.HasIndex("Agent", "ContentHash");

                    b.ToTable("OptimizationProposalEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.OptimizationTheory.OptimizationTheoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ABTestRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Agent")
                        .HasColumnType("uuid");

                    b.Property<double?>("BaselinePassRate")
                        .HasColumnType("double precision");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceTestRunIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<double?>("PValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double?>("ProjectedPassRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResultingProposalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Suite")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ABTestRunId");

                    b.HasIndex("Agent");

                    b.HasIndex("Kind");

                    b.HasIndex("ResultingProposalId");

                    b.HasIndex("Status");

                    b.HasIndex("Suite");

                    b.HasIndex("Agent", "ContentHash");

                    b.ToTable("OptimizationTheoryEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SystemEndpoint")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SystemEndpoint");

                    b.ToTable("ProjectEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Project.ProjectUserEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUserEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ProjectSearchSettings.ProjectSearchSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoReindexOnChange")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IndexedKinds")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid");

                    b.Property<int>("SnippetLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Project")
                        .IsUnique();

                    b.ToTable("ProjectSearchSettingsEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Statistics.TestRunStatsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Passed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RunCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("uuid");

                    b.Property<int>("TestCases")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid");

                    b.Property<long?>("TotalDurationMicroseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("EndpointId");

                    b.HasIndex("GroupId");

                    b.HasIndex("RunCompletedAt");

                    b.HasIndex("SuiteId");

                    b.HasIndex("TestRunId")
                        .IsUnique();

                    b.ToTable("TestRunStatsEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestCase.TestCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TestCaseEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestResult.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Evaluations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TestCase")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TestCase");

                    b.ToTable("TestResultEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestRun.TestRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Endpoint")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Group")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("Group");

                    b.ToTable("TestRunEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystemRun")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Suite")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Suite");

                    b.ToTable("TestRunGroupEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Agent")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Agent");

                    b.ToTable("TestSuiteEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEvaluatorEntity", b =>
                {
                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uuid");

                    b.HasKey("TestSuiteId", "EvaluatorId");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("TestSuiteEvaluatorEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasFilter("\"ExternalSubject\" IS NOT NULL");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("Endpoint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.AgentCall.AgentCallEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.AgentVersion.AgentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.AgentVersion.AgentVersionEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ApiKey.ApiKeyEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("Provider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Invite.InviteEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Model.ModelEntity", null)
                        .WithMany()
                        .HasForeignKey("Model")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("Provider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.OptimizationProposal.OptimizationProposalEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestRun.TestRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ABTestRun")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.AgentVersion.AgentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("AdoptedAgentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.OptimizationTheory.OptimizationTheoryEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestRun.TestRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ABTestRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.OptimizationProposal.OptimizationProposalEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultingProposalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany()
                        .HasForeignKey("Suite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemEndpoint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Project.ProjectUserEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.ProjectSearchSettings.ProjectSearchSettingsEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Statistics.TestRunStatsEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestRun.TestRunEntity", null)
                        .WithOne()
                        .HasForeignKey("Proxytrace.Storage.Internal.Entities.Statistics.TestRunStatsEntity", "TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestResult.TestResultEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestCase.TestCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("TestCase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestRun.TestRunEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("Endpoint")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("Group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany()
                        .HasForeignKey("Suite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEvaluatorEntity", b =>
                {
                    b.HasOne("Proxytrace.Storage.Internal.Entities.Evaluator.EvaluatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany("TestSuiteEvaluators")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Proxytrace.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.Navigation("TestSuiteEvaluators");
                });
#pragma warning restore 612, 618
        }
    }
}
