import { msg } from '@lingui/core/macro';
import type { MessageDescriptor } from '@lingui/core';
import { AuditAction, AuditActorType, AuditOutcome } from '../../api/models';

export const AUDIT_ACTION_LABEL: Record<AuditAction, MessageDescriptor> = {
  [AuditAction.TestRunStarted]: msg`Test Run Started`,
  [AuditAction.ApiKeyMinted]: msg`API Key Created`,
  [AuditAction.ApiKeyDeleted]: msg`API Key Deleted`,
  [AuditAction.ProjectDeleted]: msg`Project Deleted`,
  [AuditAction.ProjectMemberAdded]: msg`Member Added`,
  [AuditAction.ProjectMemberRemoved]: msg`Member Removed`,
  [AuditAction.LicenseSet]: msg`License Set`,
  [AuditAction.LicenseRemoved]: msg`License Removed`,
  [AuditAction.TestSuiteDeleted]: msg`Test Suite Deleted`,
  [AuditAction.EvaluatorDeleted]: msg`Evaluator Deleted`,
  [AuditAction.TestCaseDeleted]: msg`Test Case Deleted`,
  [AuditAction.ProviderConfigCreated]: msg`Provider Config Created`,
  [AuditAction.ProviderConfigUpdated]: msg`Provider Config Updated`,
  [AuditAction.EndpointConfigCreated]: msg`Endpoint Config Created`,
  [AuditAction.EndpointConfigUpdated]: msg`Endpoint Config Updated`,
  [AuditAction.ProviderConfigDeleted]: msg`Provider Config Deleted`,
  [AuditAction.EndpointConfigDeleted]: msg`Endpoint Config Deleted`,
  [AuditAction.UserRoleChanged]: msg`User Role Changed`,
  [AuditAction.UserDeleted]: msg`User Deleted`,
  [AuditAction.AgentDeleted]: msg`Agent Deleted`,
  [AuditAction.ProjectCreated]: msg`Project Created`,
  [AuditAction.ProjectRenamed]: msg`Project Renamed`,
  [AuditAction.AgentEndpointChanged]: msg`Agent Endpoint Changed`,
  [AuditAction.EvaluatorCreated]: msg`Evaluator Created`,
  [AuditAction.EvaluatorUpdated]: msg`Evaluator Updated`,
  [AuditAction.TestSuiteCreated]: msg`Test Suite Created`,
  [AuditAction.TestSuiteUpdated]: msg`Test Suite Updated`,
  [AuditAction.TestCaseCreated]: msg`Test Case Created`,
  [AuditAction.TestCaseUpdated]: msg`Test Case Updated`,
  [AuditAction.UserInvited]: msg`User Invited`,
  [AuditAction.InviteRevoked]: msg`Invite Revoked`,
  [AuditAction.UserSignedUp]: msg`User Signed Up`,
  [AuditAction.UserLoggedIn]: msg`Signed In`,
  [AuditAction.LoginFailed]: msg`Failed Sign-In`,
  [AuditAction.UserLoggedOut]: msg`Signed Out`,
  [AuditAction.AdminBootstrapped]: msg`Admin Created`,
  [AuditAction.LegacyAccountClaimed]: msg`Account Claimed`,
  [AuditAction.ProposalStatusChanged]: msg`Proposal Status Changed`,
  [AuditAction.EmailSettingsUpdated]: msg`Email Settings Updated`,
  [AuditAction.OutlierSettingsUpdated]: msg`Outlier Settings Updated`,
  [AuditAction.PasswordResetRequested]: msg`Password Reset Requested`,
  [AuditAction.PasswordResetCompleted]: msg`Password Reset Completed`,
  [AuditAction.PasswordResetLinkIssued]: msg`Password Reset Link Issued`,
  [AuditAction.TheorySubmitted]: msg`Theory Submitted`,
  [AuditAction.TheoryReset]: msg`Theory Reset`,
  [AuditAction.TheoryRejected]: msg`Theory Rejected`,
  [AuditAction.TheoryValidated]: msg`Theory Validated`,
  [AuditAction.TheoryInvalidated]: msg`Theory Invalidated`,
  [AuditAction.ProposalGenerated]: msg`Proposal Generated`,
  [AuditAction.ProposalAutoAdopted]: msg`Proposal Auto-Adopted`,
  [AuditAction.TestRunGroupOptimizeRequested]: msg`Optimization Requested`,
  [AuditAction.TestRunGroupCancelled]: msg`Test Run Cancelled`,
  [AuditAction.TestRunGroupDeleted]: msg`Test Run Group Deleted`,
  [AuditAction.TestRunDeleted]: msg`Test Run Deleted`,
  [AuditAction.TestRunScheduleCreated]: msg`Schedule Created`,
  [AuditAction.TestRunScheduleUpdated]: msg`Schedule Updated`,
  [AuditAction.TestRunScheduleDeleted]: msg`Schedule Deleted`,
  [AuditAction.TestRunScheduleRunNow]: msg`Schedule Run Now`,
  [AuditAction.AgentCallDeleted]: msg`Trace Deleted`,
  [AuditAction.AgentVersionMoved]: msg`Agent Version Moved`,
  [AuditAction.SetupCleanupPurged]: msg`Data Purged`,
  [AuditAction.SecretsBackfilled]: msg`Secrets Backfilled`,
  [AuditAction.AccessDenied]: msg`Access Denied`,
};

export const AUDIT_ACTOR_TYPE_LABEL: Record<AuditActorType, MessageDescriptor> = {
  [AuditActorType.User]: msg`User`,
  [AuditActorType.ApiKey]: msg`API Key`,
  [AuditActorType.System]: msg`System`,
};

export const AUDIT_OUTCOME_LABEL: Record<AuditOutcome, MessageDescriptor> = {
  [AuditOutcome.Success]: msg`Success`,
  [AuditOutcome.Failure]: msg`Failure`,
};

export const ACTION_COLOR: Record<AuditAction, string> = {
  [AuditAction.TestRunStarted]: 'var(--teal)',
  [AuditAction.ApiKeyMinted]: 'var(--success)',
  [AuditAction.ApiKeyDeleted]: 'var(--danger)',
  [AuditAction.ProjectDeleted]: 'var(--danger)',
  [AuditAction.ProjectMemberAdded]: 'var(--accent-primary)',
  [AuditAction.ProjectMemberRemoved]: 'var(--accent-primary)',
  [AuditAction.LicenseSet]: 'var(--accent-primary)',
  [AuditAction.LicenseRemoved]: 'var(--accent-primary)',
  [AuditAction.TestSuiteDeleted]: 'var(--danger)',
  [AuditAction.EvaluatorDeleted]: 'var(--danger)',
  [AuditAction.TestCaseDeleted]: 'var(--danger)',
  [AuditAction.ProviderConfigCreated]: 'var(--success)',
  [AuditAction.ProviderConfigUpdated]: 'var(--warn)',
  [AuditAction.EndpointConfigCreated]: 'var(--success)',
  [AuditAction.EndpointConfigUpdated]: 'var(--warn)',
  [AuditAction.ProviderConfigDeleted]: 'var(--danger)',
  [AuditAction.EndpointConfigDeleted]: 'var(--danger)',
  [AuditAction.UserRoleChanged]: 'var(--accent-primary)',
  [AuditAction.UserDeleted]: 'var(--danger)',
  [AuditAction.AgentDeleted]: 'var(--danger)',
  [AuditAction.ProjectCreated]: 'var(--success)',
  [AuditAction.ProjectRenamed]: 'var(--warn)',
  [AuditAction.AgentEndpointChanged]: 'var(--warn)',
  [AuditAction.EvaluatorCreated]: 'var(--success)',
  [AuditAction.EvaluatorUpdated]: 'var(--warn)',
  [AuditAction.TestSuiteCreated]: 'var(--success)',
  [AuditAction.TestSuiteUpdated]: 'var(--warn)',
  [AuditAction.TestCaseCreated]: 'var(--success)',
  [AuditAction.TestCaseUpdated]: 'var(--warn)',
  [AuditAction.UserInvited]: 'var(--accent-primary)',
  [AuditAction.InviteRevoked]: 'var(--danger)',
  [AuditAction.UserSignedUp]: 'var(--success)',
  [AuditAction.UserLoggedIn]: 'var(--teal)',
  [AuditAction.LoginFailed]: 'var(--danger)',
  [AuditAction.UserLoggedOut]: 'var(--accent-primary)',
  [AuditAction.AdminBootstrapped]: 'var(--accent-primary)',
  [AuditAction.LegacyAccountClaimed]: 'var(--accent-primary)',
  [AuditAction.ProposalStatusChanged]: 'var(--teal)',
  [AuditAction.EmailSettingsUpdated]: 'var(--warn)',
  [AuditAction.OutlierSettingsUpdated]: 'var(--warn)',
  [AuditAction.PasswordResetRequested]: 'var(--warn)',
  [AuditAction.PasswordResetCompleted]: 'var(--success)',
  [AuditAction.PasswordResetLinkIssued]: 'var(--accent-primary)',
  [AuditAction.TheorySubmitted]: 'var(--accent-primary)',
  [AuditAction.TheoryReset]: 'var(--warn)',
  [AuditAction.TheoryRejected]: 'var(--danger)',
  [AuditAction.TheoryValidated]: 'var(--success)',
  [AuditAction.TheoryInvalidated]: 'var(--warn)',
  [AuditAction.ProposalGenerated]: 'var(--teal)',
  [AuditAction.ProposalAutoAdopted]: 'var(--teal)',
  [AuditAction.TestRunGroupOptimizeRequested]: 'var(--accent-primary)',
  [AuditAction.TestRunGroupCancelled]: 'var(--warn)',
  [AuditAction.TestRunGroupDeleted]: 'var(--danger)',
  [AuditAction.TestRunDeleted]: 'var(--danger)',
  [AuditAction.TestRunScheduleCreated]: 'var(--success)',
  [AuditAction.TestRunScheduleUpdated]: 'var(--warn)',
  [AuditAction.TestRunScheduleDeleted]: 'var(--danger)',
  [AuditAction.TestRunScheduleRunNow]: 'var(--teal)',
  [AuditAction.AgentCallDeleted]: 'var(--danger)',
  [AuditAction.AgentVersionMoved]: 'var(--warn)',
  [AuditAction.SetupCleanupPurged]: 'var(--danger)',
  [AuditAction.SecretsBackfilled]: 'var(--accent-primary)',
  [AuditAction.AccessDenied]: 'var(--danger)',
};
