//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Proxytrace.Application {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Prompts {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("Proxytrace.Application.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string agent_name_generator {
            get {
                return ResourceManager.GetString("agent_name_generator", resourceCulture);
            }
        }
        
        internal static string update_system_prompt_optimizer {
            get {
                return ResourceManager.GetString("update_system_prompt_optimizer", resourceCulture);
            }
        }
        
        internal static string update_tool_definition_optimizer {
            get {
                return ResourceManager.GetString("update_tool_definition_optimizer", resourceCulture);
            }
        }

        internal static string politeness_evaluator {
            get {
                return ResourceManager.GetString("politeness_evaluator", resourceCulture);
            }
        }

        internal static string safety_classifier {
            get {
                return ResourceManager.GetString("safety_classifier", resourceCulture);
            }
        }

        internal static string tool_usage_evaluator {
            get {
                return ResourceManager.GetString("tool_usage_evaluator", resourceCulture);
            }
        }

        internal static string helpfulness_evaluator {
            get {
                return ResourceManager.GetString("helpfulness_evaluator", resourceCulture);
            }
        }
    }
}
