namespace Proxytrace.Domain.OptimizationTheory;

/// <summary>
/// Identifies who produced an <see cref="IOptimizationTheory"/>.
/// Theories enter a single shared validation pipeline regardless of origin.
/// </summary>
public enum TheorySource
{
    /// <summary>Generated by a built-in optimizer from test-run evidence.</summary>
    Optimizer,

    /// <summary>Submitted manually by a human user.</summary>
    User,

    /// <summary>Submitted by the Tracey AI assistant.</summary>
    TraceyAi,

    /// <summary>Submitted by an external third-party caller via the API.</summary>
    External,
}
