// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trsr.Storage;

#nullable disable

namespace Trsr.Storage.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20260507174959_AddProjectUserMembership")]
    partial class AddProjectUserMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Agent.AgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemAgent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Project")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.ToTable("AgentEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.AgentCall.AgentCallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<ulong?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EndpointId");

                    b.ToTable("AgentCallEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.ApiKey.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Project")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Project");

                    b.HasIndex("Provider");

                    b.ToTable("ApiKeyEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Evaluator.EvaluatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Project")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("EvaluatorEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Model.ModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InputTokenCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Model")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OutputTokenCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("Model", "Provider")
                        .IsUnique();

                    b.ToTable("ModelEndpointEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelProviderEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.OptimizationProposal.OptimizationProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Agent")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceTestRunIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Agent");

                    b.HasIndex("Kind");

                    b.HasIndex("Status");

                    b.ToTable("OptimizationProposalEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SystemEndpoint");

                    b.ToTable("ProjectEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Project.ProjectUserEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUserEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestCase.TestCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestCaseEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestResult.TestResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evaluations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TestCase")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestCase");

                    b.ToTable("TestResultEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestRun.TestRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Group")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StatCost")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StatInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StatOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatTestCases")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StatTotalDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("Group");

                    b.ToTable("TestRunEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Suite")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Suite");

                    b.ToTable("TestRunGroupEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Agent")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Agent");

                    b.ToTable("TestSuiteEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEvaluatorEntity", b =>
                {
                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestSuiteEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("TestSuiteId", "EvaluatorId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("TestSuiteEntityId");

                    b.ToTable("TestSuiteEvaluatorEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Agent.AgentEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("Endpoint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.AgentCall.AgentCallEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.ApiKey.ApiKeyEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("Provider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Model.ModelEntity", null)
                        .WithMany()
                        .HasForeignKey("Model")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.ModelProvider.ModelProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("Provider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.OptimizationProposal.OptimizationProposalEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemEndpoint")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Project.ProjectUserEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Project.ProjectEntity", null)
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestResult.TestResultEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.TestCase.TestCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("TestCase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestRun.TestRunEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.ModelEndpoint.ModelEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("Endpoint")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", null)
                        .WithMany()
                        .HasForeignKey("Group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestRunGroup.TestRunGroupEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany()
                        .HasForeignKey("Suite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Agent.AgentEntity", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEvaluatorEntity", b =>
                {
                    b.HasOne("Trsr.Storage.Internal.Entities.Evaluator.EvaluatorEntity", null)
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany("TestSuiteEvaluators")
                        .HasForeignKey("TestSuiteEntityId");

                    b.HasOne("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", null)
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.Project.ProjectEntity", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Trsr.Storage.Internal.Entities.TestSuite.TestSuiteEntity", b =>
                {
                    b.Navigation("TestSuiteEvaluators");
                });
#pragma warning restore 612, 618
        }
    }
}
