// Reads the VitePress manual markdown (manual/guide/*.md + manual/admin/*.md), builds the
// searchable docs index, and writes it as a typed TS module bundled into the frontend so
// Tracey's in-browser `search_docs` tool can answer from the product manual. Run via
// `npm run gen:docs` (also invoked by predev/prebuild/pretest). The output file is a build
// artifact (git-ignored) — never edit it by hand.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDocsIndex } from './build-docs-index.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(here, '..', '..');
const manualRoot = join(frontendRoot, '..', 'manual');
const outFile = join(frontendRoot, 'src', 'features', 'tracey', 'knowledge', 'docs-index.generated.ts');

const SECTIONS = ['guide', 'admin'];

/** @type {{ relPath: string, content: string }[]} */
const files = [];
for (const section of SECTIONS) {
  const dir = join(manualRoot, section);
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.md')) continue;
    files.push({
      relPath: `${section}/${name}`,
      content: readFileSync(join(dir, name), 'utf8'),
    });
  }
}
files.sort((a, b) => a.relPath.localeCompare(b.relPath));

const index = buildDocsIndex(files);

const banner = `// GENERATED by scripts/docs-index/generate.mjs from the VitePress manual — DO NOT EDIT.
// Run \`npm run gen:docs\` to regenerate. Source: manual/guide/*.md, manual/admin/*.md.
`;
const contents = `${banner}import type { DocSection } from './types';

export const DOCS_INDEX: DocSection[] = ${JSON.stringify(index, null, 2)};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, contents);

console.log(`docs-index: ${index.length} sections from ${files.length} pages -> ${outFile}`);
